language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.5"
  - "pypy"

branches:
  only:
    - master

install:
  - CFLAGS=-I/usr/local/opt/icu4c/include LDFLAGS=-L/usr/local/opt/icu4c/lib pip install pyicu;

script:
  - python setup.py install
